.\"
.\" Copyright (c) 2007 Mikolaj Golub
.\"	All rights reserved.
.\" 
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $Id: bsnmp-ucd.8,v 1.5 2008/01/20 13:40:41 mikolaj Exp $
.\"
.Dd December, 2007
.Dt bsnmp-ucd 8
.Os bsnmp-ucd
.Sh NAME
.Nm bsnmp-ucd
.Nd an SNMP module which implements parts of UCD-SNMP-MIB.
.Sh DESCRIPTION
.Nm
is a module for 
.Xr bsnmpd 1
which allows to get memory, load average, cpu usage and other system
statistics. It implements parts of UCD-SNMP-MIB for this.
.Pp
.Sh OPTIONS
To activate the
.Nm
module add this string to
.Pa /etc/snmpd.config:
.Bd -literal -offset indent
begemotSnmpdModulePath."ucd" = "/usr/local/lib/snmp_ucd.so"
.Ed
.Pp
.Sh MIBS
The counters will be available under the following MIB:
.Bd -literal -offset indent
 .1.3.6.1.4.1.2021
.Ed
.Pp 
Or if the appropriate MIB file has been installed:
.Bd -literal -offset indent
UCD-SNMP-MIB::ucdavis
.Ed
.Pp
With
.Nm
you can also extend bsnmpd agent functionality specifying arbitrary
commands in UCD-SNMP-MIB::extTable. To add new command you should add
following lines in snmpd.conf in
.Nm
module section:
.Bd -literal -offset indent
extNames.<INDEX> = <name>
extCommand.<INDEX> = <commandline>
.Ed
.Pp
For example, to collect lastpid statistics under mib
UCD-SNMP-MIB::extOutput.0 you can specify:
.Bd -literal -offset indent
extNames.0 = "lastpid"
extCommand.0 = "/sbin/sysctl -n kern.lastpid"
.Ed
.Pp
Note: Index order is important. Commands should be indexed beginning
from 0 and without gaps.
.Pp
When program finished, the exit status is available via extResult mib
and the first line of output is placed in extOutupt mib. The next time
the program will be run only after some period of time (this period is
set in sources and can be changed only by recompiling module).
.Pp
It is possible to specify command that will be run to fix
problem when extension command returns nonzero status. For this,
together with previous two mibs for extension command, the following
mibs should be set:
.Bd -literal -offset indent
extErrFix.<INDEX> = 1
extErrFixCmd.<INDEX> = <fix command>
.Ed
.Pp
For example, to monitor apache and restart process when it is down,
you can add to configuration file:
.Bd -literal -offset indent
extNames.1 = "apache"
extCommand.1 = "/usr/local/etc/rc.d/apache status"
extErrFix.1 = 1
extErrFixCmd.1 = "/usr/local/etc/rc.d/apache restart"
.Ed
.Sh SEE ALSO
.Xr bsnmpd 1 
.Sh AUTHOR
.An Mikolaj Golub
.Sh BUGS
extTable is rather experimental feature at this moment.
